language: python
python:
  - "3.5.1"
# command to install dependencies
#before_install:
#  - "sudo apt-get install -qq"
install:
  - "pip install pytest pyflakes pip pep8 coverage"
  - "python setup.py install"    
# command to run tests
script: "env PYTHONPATH=.:$PYTHONPATH py.test -v"
notifications:
  email: false
