language: python
python:
  - "3.7.4"
# command to install dependencies
#before_install:
#  - "sudo apt-get install -qq"
install:
  - "pip install pytest pyflakes pip pep8 coverage pytest-pep8 pytest-cov pytest-flakes"
  - "python setup.py install"    
# command to run tests
script: "./scripts/run_tests.sh"
notifications:
  email: false
