language: python
python:
  - "3.7.4"
  - "3.8"
# command to install dependencies
#before_install:
#  - "sudo apt-get install -qq"
install:
  - "pip install pytest pyflakes pip pep8 coverage pytest-pep8 pytest-cov pytest-flakes rstcheck codecov"
  - "python setup.py install"
# command to run tests
script: "./scripts/run_tests.sh --cov lindh --cov-report html"
notifications:
  email: false
after_success:
  - codecov
